apiVersion: v1
kind: ConfigMap
metadata:
  name: archetype-config
  namespace: archetype-dev
data:
  APP_NAME: "archetype"
  APP_VERSION: "1.0.0"
  APP_REVISION: "unknown"
  APP_BUILT_AT: "unknown"
  APP_REST_HOST: "0.0.0.0"
  APP_REST_PORT: "8080"
  APP_DATA_DIR: "/data"
  APP_DB_HOST: "db-postgres-cluster-001-do-user-18951983-0.f.db.ondigitalocean.com"
  APP_DB_PORT: "25060"
  APP_DB_NAME: "archetype"
  APP_DB_USER: "archetype_user"
  APP_DB_SSLMODE: "require"
  APP_DB_ADDR: "db-postgres-cluster-001-do-user-18951983-0.f.db.ondigitalocean.com:25060"
  APP_CHECK_SERVICE_URLS: "https://api.github.com,https://status.stripe.com"
