apiVersion: v1
kind: ConfigMap
metadata:
  name: archetype-config
  namespace: archetype-dev
data:
  PORT: "8080"
  APP_PORT: "8080"
  VERSION: "1.0.0"
  REVISION: "unknown"
  BUILT_AT: "unknown"
  DATA_DIR: "/data"
  DB_HOST: "db-postgres-cluster-001-do-user-18951983-0.f.db.ondigitalocean.com"
  DB_PORT: "25060"
  DB_NAME: "archetype"
  DB_USER: "archetype_user"
  DB_SSLMODE: "require"
  DB_ADDR: "db-postgres-cluster-001-do-user-18951983-0.f.db.ondigitalocean.com:25060"
  CHECK_SERVICE_URLS: "https://api.github.com,https://status.stripe.com"
  CHECK_TIMEOUT_MS: "1500"
