apiVersion: v1
kind: PersistentVolume
metadata:
  name: archetype-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: do-block-storage
  csi:
    driver: dobs.csi.digitalocean.com
    volumeHandle: 075c119f-df9d-11ef-8298-0a58ac14290b
    fsType: ext4
