apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archetype-pvc
  namespace: archetype-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
  volumeName: archetype-pv
